S65-131: Add dotnetcore workflow, Default Dockerfile
S65-2-project/AuthenticationService pull request #4
Opened 2020-04-07 12:12 UTC by davydehaas98

2020-04-17 07:36 UTC, FlorisFeddema requested changes
Comments plaatsen.

2020-04-17 07:36 UTC, FlorisFeddema commented on .github/workflows/dotnetcore.push.yml
> +      - "*/*"
Zalt dat niet in hetgeen op regel 6?

2020-04-17 07:36 UTC, FlorisFeddema commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-bionic
Waarom geen buildcontainers gebruiken?

2020-04-17 07:41 UTC, davydehaas98 commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-bionic
Dit wordt gedaan bij runs-on: container:

2020-04-24 12:12 UTC, FlorisFeddema reviewed
Dockerfile comments

2020-04-24 12:12 UTC, FlorisFeddema commented on Dockerfile
> +FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.3-bionic
Hier even comments

2020-05-04 08:42 UTC, FlorisFeddema approved these changes

2020-05-04 08:42 UTC, merged