Feature/s65 97
S65-2-project/AuthenticationService pull request #7
Opened 2020-04-17 12:53 UTC by WouterVan

2020-04-17 13:31 UTC, FlorisFeddema requested changes

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/MessageHandlers/RegisterUserMessageHandler.cs
> +        private IMessageQueuePublisher _publisher;
readonly maken

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/MessageHandlers/RegisterUserMessageHandler.cs
> +           // _publisher.PublishMessageAsync("routingkey", "messagetype", "value");
comment weghalen, die informatie hoort in het interface te staan

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Messaging/ConnectionBuilder.cs
> +        public static void AddMessageConsumer(this IServiceCollection services, string queueName , Action<MessagingBuilder> builderFn = null)
Comments?

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Messaging/ConnectionBuilder.cs
> +        public static void AddMessageConsumer(this IServiceCollection services, string queueName , Action<MessagingBuilder> builderFn = null)
Lastige, complexe code heeft wel comments nodig om te snappen te zijn

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Messaging/IMessageHandler.cs
> +        public interface IMessageHandler<TMessage> : IMessageHandler
Dit in een ander bestand, liefst gewoon 1 class/interface per bestand

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Messaging/IMessageHandler.cs
> +        public interface IMessageHandler<TMessage> : IMessageHandler
Alhoewel het hier wel kan omdat ze dezelfde naam hebben

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Messaging/IMessageQueuePublisher.cs
> +        Task PublishMessageAsync<T>(string routingKey, string messageType, T value);
.NETdoc ALTIJD op interfaces

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Program.cs
> +            // RabbitConnectionFactory factory = new RabbitConnectionFactory();
Clean de code op

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Repositories/IUserRepository.cs
> +        Task<User> Create(User user);
Comments

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationService/Services/UserService.cs
> +            var tempEmail = await _repository.Get(email);
temp email? en op 25 tempid?

2020-04-17 13:31 UTC, FlorisFeddema commented on AuthenticationServiceTest/Helpers/HasherTest.cs
> +        private IHasher _hasher;
readonly

2020-04-17 13:45 UTC, davydehaas98 requested changes
Er zijn geen tests voor RabbitMQ?

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/MessageHandlers/RegisterUserMessageHandler.cs
> +        /// recieves messages send to messagetype RegisterUser
Receives ipv recieves

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/MessageHandlers/RegisterUserMessageHandler.cs
> +           // _publisher.PublishMessageAsync("routingkey", "messagetype", "value");
Waarom is dit gecomment

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/MessageModels/RegisterUser.cs
> +
Let op random whitespacing met het schrijven van code :D

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/QueueName.cs
> +        public QueueName(string name)
Whitespacing tussen variables en constructors

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/RabbitConnectionFactory.cs
> +
Onnodige whitespace!!!

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/RabbitConnectionFactory.cs
> +
Doubt

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/RabbitQueueReader.cs
> +        }
Space

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/RabbitQueueReader.cs
> +
Witte ruimte

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/RabbitQueueReader.cs
> +
More white

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Messaging/IMessageQueuePublisher.cs
> +
Blanke leegte

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Repositories/IUserRepository.cs
> +    public interface IUserRepository
XML Documentation?

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Program.cs
> +            // RabbitQueueReader queue = new RabbitQueueReader(factory);
Uitgecomment omdat?

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Repositories/IUserRepository.cs
> +        Task<User> Create(User user);
Spacing

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Repositories/UserRepository.cs
> +namespace AuthenticationService.Repositories
Spacing tussen elke methode en constructor

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Services/UserService.cs
> +
Space :(

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationServiceTest/Helpers/HasherTest.cs
> +
:(

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationService/Startup.cs
> +
:o

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationServiceTest/Helpers/HasherTest.cs
> +    public class HasherTest
Zorg ervoor dat je een naming scheme aanhoud, zoals TestedMethod_Input_Return of VerifyHash_InvalidPassword_ThrowInvalidPasswordException/VerifyHash_InvalidSalt_ThrowInvalidSaltException

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationServiceTest/Helpers/HasherTest.cs
> +    public class HasherTest
Dit zorgt voor sneller kunnen zien wat er wordt getest in een lijstje etcetera en welke parameters er worden gezet met bijbehorende results.

2020-04-17 13:45 UTC, davydehaas98 commented on AuthenticationServiceTest/Services/UserServiceTest.cs
> +
Two :o

2020-04-24 12:22 UTC, WouterVan commented
Fiixed all non unit test related requested changes

2020-04-24 12:22 UTC, davydehaas98 approved these changes

2020-04-24 12:26 UTC, FlorisFeddema approved these changes

2020-04-24 12:26 UTC, merged